export const topics = [
  { slug: 'semantic-search', label: 'Semantic search', title: 'Find the idea. Even when the words are different.', description: 'Discover how Knowdexia combines semantic document search and keyword matching to find relevant passages across your knowledge library.', intro: 'The words in your question are not always the words in your documents. Semantic search helps bridge that gap by comparing meaning, while keyword matching keeps exact terms useful.', sections: [
    ['From wording to meaning', 'A question about “visibility in AI recommendations” may relate to passages about LLM visibility, AI discovery, recommendation relevance, generative search optimization, or model citations. Those are illustrative connections, not guaranteed matches: results depend on your documents and their relevance.'],
    ['Why combine semantic and keyword search?', 'Meaning matters for open questions. Exact wording matters for a product name, an identifier, or a specific term. Knowdexia combines semantic similarity with BM25 keyword retrieval, then ranks relevant passages from the selected scope.'],
    ['Keep the result connected to its source', 'Search results retain the document name and available location information. Open a result to inspect its passage in the document viewer. Search your whole library, a collection, or selected documents.']
  ] },
  { slug: 'ai-knowledge-base', label: 'AI knowledge base', title: 'A knowledge base that helps you find answers.', description: 'Build a persistent AI knowledge base from your documents, with collections, library-wide retrieval, and answers linked to sources.', intro: 'A folder stores files. An AI knowledge base also makes their contents retrievable. Knowdexia brings your documents into a persistent library that you can search and question.', sections: [
    ['Start with the material you already have', 'Upload PDFs, Word documents, spreadsheets, Markdown, HTML, and plain text. Knowdexia extracts readable content, divides it into passages, and indexes those passages for retrieval. Image-only scans need text extraction before upload; OCR is not a current feature.'],
    ['Give your library a useful shape', 'Group related material into collections, such as product documentation, research, or reports. You can move documents between collections and limit a search to the material relevant to your task.'],
    ['Ask with evidence in reach', 'With an AI provider configured, Knowdexia uses retrieved passages to generate cited answers. Without a provider, it can return a cited extract. In either case, inspect the source before relying on an answer.']
  ] },
  { slug: 'document-search', label: 'Document search', title: 'Find the passage. Not just the file.', description: 'Search inside PDFs, DOCX files, spreadsheets, notes, and reports with semantic and keyword document search in Knowdexia.', intro: 'Finding a filename is only the beginning. Knowdexia searches the content inside supported documents and lets you open the passage that made a result relevant.', sections: [
    ['Search across different formats', 'Bring together text-based PDFs, DOCX, XLSX, XLS, CSV, Markdown, HTML, and TXT files. Supported formats share a retrieval workflow, so a question can surface a paragraph in a report alongside a relevant spreadsheet passage.'],
    ['Read results in context', 'Each result carries a document name, a snippet, and available source location information. Depending on the format, that may include a page, heading, sheet, or row. The viewer helps you inspect the supporting passage.'],
    ['Know the limits of extraction', 'Search quality depends on readable source text. Complex layouts and spreadsheet structure can affect extraction. Knowdexia does not currently perform OCR, so image-only PDFs need a text layer before they can be usefully searched.']
  ] },
  { slug: 'multi-document-search', label: 'Multi-document search', title: 'One question. More than one document.', description: 'Search and ask across multiple documents in Knowdexia, with scoped retrieval and source citations from your knowledge library.', intro: 'Useful answers often live across several files. Multi-document search retrieves passages from a set of documents instead of restricting every question to a single upload.', sections: [
    ['Choose the scope of your question', 'Search the entire library for a broad investigation. Select a collection for a project, choose a set of documents for comparison, or narrow to one document when you already know where to look.'],
    ['Bring relevant passages together', 'Knowdexia ranks passages across the selected scope. With a configured AI provider, the answer can combine information from multiple retrieved documents and cite the passages it uses. It does not necessarily read every page of every file for each question.'],
    ['Check each source independently', 'A cross-document answer should still be traceable to individual evidence. Follow its citations to inspect each passage, check dates and assumptions, and identify differences that need closer review.']
  ] },
  { slug: 'knowledge-management', label: 'Knowledge management', title: 'Make what you know easier to find again.', description: 'Organize documents into persistent collections and make your knowledge searchable with Knowdexia’s document-centered knowledge management.', intro: 'Knowledge management starts with keeping important material accessible. Knowdexia adds content retrieval and cited answers to a persistent document library.', sections: [
    ['Organize around your work', 'Use collections for a research area, a product, a project, or a set of reports. These groupings also become search scopes, so organization helps control which material informs a result.'],
    ['Keep a library, not a temporary conversation', 'Uploaded documents and their indexes persist in the current local application. Add files as your work develops, move them into collections, and delete documents that are no longer useful.'],
    ['Understand the current scope', 'Knowdexia currently focuses on uploaded documents, collections, retrieval, and source navigation. Shared team workspaces, hosted accounts, and external content connectors are not available in the inspected application.']
  ] },
  { slug: 'ai-second-brain', label: 'AI second brain', title: 'Keep the knowledge. Find the connection.', description: 'Use Knowdexia as a document-based AI second brain: collect useful material, search by meaning, and revisit the evidence behind answers.', intro: 'Your second brain should help you return to what you have learned. Knowdexia makes a collection of documents searchable, so useful material is easier to recover when a new question appears.', sections: [
    ['Collect deliberately', 'Bring in research, technical notes, reports, and other supported documents you want to revisit. Collections help keep a growing library organized around subjects that matter to you.'],
    ['Retrieve without remembering the exact phrase', 'Ask a natural-language question or search for a concept. Semantic retrieval can help uncover related wording; keyword retrieval also helps with precise terms. The system searches the material you provide.'],
    ['Use AI as a starting point for understanding', 'Generated answers require a configured AI provider and draw on retrieved passages. Citations give you a path back to those passages. Knowdexia does not currently create an automatic knowledge graph or extract a network of entities.']
  ] },
  { slug: 'rag-document-search', label: 'RAG document search', title: 'Retrieval first. Answers with references.', description: 'Understand Knowdexia’s cross-document RAG workflow: scoped retrieval, relevant passages, AI generation, and navigable source citations.', intro: 'Retrieval-augmented generation (RAG) supplies an AI model with relevant source passages before it answers. Knowdexia applies this workflow across a document library.', sections: [
    ['Retrieve within a defined scope', 'The question is matched against indexed passages using semantic and keyword retrieval. Ranking selects relevant passages from the chosen library, collection, document set, or individual document.'],
    ['Generate from numbered source passages', 'When an AI provider is configured, Knowdexia sends selected passages with source information to the model and asks for a cited answer. Without a provider, the built-in path can select a verbatim answer from the retrieved material.'],
    ['Validate references, then inspect the evidence', 'The application removes citation numbers that do not reference the supplied context and declines a generated answer with no valid citation. This checks reference validity, not the truth of every claim. Users should still inspect whether the cited passage supports the answer.']
  ] },
  { slug: 'search-across-documents', label: 'Search across documents', title: 'Stop opening files one at a time.', description: 'A practical workflow for searching across documents: upload, organize, choose a scope, and inspect relevant passages in Knowdexia.', intro: 'When you do not know which file holds the answer, start with the whole library. Narrow your scope as you discover which material is relevant.', sections: [
    ['1. Add a useful starting set', 'Upload supported documents related to your question. For a project review, this might mean research notes, product requirements, technical designs, and spreadsheet reports. Confirm the files are indexed before searching.'],
    ['2. Search broadly, then narrow', 'Start with a concept or a natural-language question. Review the document names and snippets that appear. Use a collection or selected documents to focus the next search on a more relevant subset.'],
    ['3. Follow the evidence', 'Open the relevant passages to understand their context. Use Ask for a cited answer when helpful, then follow its citations back to the documents. Keep the original evidence part of your decision.']
  ] }
];
