import { topics } from './content.mjs';
import { questions } from '../demo-data.js';
import { renderAnswer, renderPreview, renderScopes, renderStatus, renderSuggestions, renderTabs } from '../demo-render.js';
export const escape = (s) => String(s).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mark = '<span class="brand-mark" aria-hidden="true">K<span></span></span>';
const brand = `<a class="brand" href="/" aria-label="Knowdexia home">${mark}<span>Knowdexia<span class="brand-dot">.</span></span></a>`;
const arrow = '<span aria-hidden="true">↗</span>';
const cta = (config) => config.comingSoon
  ? `<a class="button primary" href="/coming-soon">Coming soon ${arrow}</a>`
  : `<a class="button primary" href="${escape(config.appUrl)}">Try Knowdexia ${arrow}</a>`;
const links = () => topics.map(t => `<a href="/${t.slug}">${t.label}</a>`).join('');
export function layout(config, { path = '/', title, description, body, noindex = false }) {
  const canonical = config.siteUrl + (path === '/' ? '/' : path);
  const schema = { '@context':'https://schema.org', '@type':'WebSite', name:'Knowdexia', url:config.siteUrl, description:'A document knowledge library with semantic search, cited answers, and source navigation.' };
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${canonical}"><meta name="robots" content="${noindex ? 'noindex, follow' : 'index, follow'}"><meta name="theme-color" content="#315bda"><meta property="og:type" content="website"><meta property="og:site_name" content="Knowdexia"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${config.siteUrl}/og.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Knowdexia — Documents to knowledge, answers to sources"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(title)}"><meta name="twitter:description" content="${escape(description)}"><meta name="twitter:image" content="${config.siteUrl}/og.png"><link rel="icon" href="/favicon.ico" sizes="48x48"><link rel="icon" type="image/png" sizes="192x192" href="/favicon-192.png"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="stylesheet" href="/style.css"><script src="/site.js" defer></script><script type="module" src="/demo.js"></script><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body><a class="skip" href="#main">Skip to content</a><header class="header"><div class="container header-inner">${brand}<button class="menu-button" aria-label="Toggle navigation" aria-expanded="false" aria-controls="navigation">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Main navigation"><a href="/#how-it-works">How it works</a><a href="/#capabilities">Capabilities</a><a href="/about">About</a></nav>${cta(config)}</div></header><main id="main">${body}</main><footer><div class="container"><div class="footer-top"><div>${brand}<p>Your documents.<br>Your knowledge. Connected.</p></div><div class="footer-links"><h2>Explore Knowdexia</h2>${links()}</div><div class="footer-links"><h2>Company & resources</h2><a href="/about">About</a><a href="/coming-soon">Get updates</a><span>Pricing <small>Planned</small></span><span>Documentation <small>Planned</small></span><span>Blog <small>Planned</small></span></div></div><div class="footer-bottom"><span>© ${new Date().getUTCFullYear()} Knowdexia</span><span><a href="/privacy">Privacy</a><a href="/terms">Terms</a></span><span>From documents to understanding.</span></div></div></footer></body></html>`;
}
function demo() {
const q = questions[0];
return `<div class="workspace" aria-label="Interactive Knowdexia example: choose a collection, ask a question, inspect the cited source"><div class="workspace-top"><span class="workspace-logo">${mark} Knowledge workspace</span><span class="demo-label">INTERACTIVE EXAMPLE</span></div><div class="workspace-body"><aside class="workspace-sidebar"><span class="tiny">YOUR LIBRARY</span><div id="demo-scopes" class="scope-list">${renderScopes('all')}</div><div class="library-note"><span class="status-dot"></span> Knowledge, connected<br><small>Across documents & formats</small></div></aside><div class="workspace-content"><form id="demo-form" class="query" role="search"><span aria-hidden="true">⌕</span><input id="demo-query" type="text" value="${escape(q.text)}" aria-label="Ask the example library a question" autocomplete="off" maxlength="160"><button class="query-arrow" type="submit" aria-label="Ask">↵</button></form><div id="demo-suggestions" class="suggestions" aria-label="Suggested questions">${renderSuggestions('all', q.id)}</div><div id="demo-status" class="retrieval" aria-live="polite">${renderStatus('all', q)}</div><div class="answer-label"><span aria-hidden="true">✳</span> FROM YOUR KNOWLEDGE</div><div id="demo-answer" aria-live="polite">${renderAnswer(q)}</div><div id="demo-tabs" class="source-tabs" aria-label="Example sources">${renderTabs(q)}</div><div class="source-preview" id="source-preview" role="region" aria-label="Selected source passage" aria-live="polite" tabindex="-1">${renderPreview(q)}</div></div></div></div>`;
}
export function home(config) {
const steps = [ ['Add your knowledge','Upload the documents you want to understand. Keep them together in your library.'],['Knowdexia understands it','Your documents are parsed and indexed for search by meaning and by keyword.'],['Search or ask','Find concepts or ask a question across your library, a collection, or selected files.'],['Verify the answer','Follow a citation back to the document and inspect the relevant source passage.'] ];
const comparisons = [['Keyword search','Yes','Sometimes','Yes'],['Semantic search','No','Yes','Yes'],['Multi-document knowledge','Limited','Varies','Yes'],['AI answers','No','Yes','With AI provider'],['Source citations','No','Sometimes','Yes'],['Navigate to evidence','Limited','Varies','Yes'],['Persistent knowledge library','No','Varies','Yes']];
return layout(config,{title:'Knowdexia — Searchable, connected knowledge from your documents',description:'Turn documents into a searchable knowledge library. Search by meaning, ask across documents, and follow cited answers back to original sources.',body:`
<section class="hero container"><div class="eyebrow"><span class="status-dot"></span> YOUR KNOWLEDGE, WITH THE CONNECTIONS INTACT</div><h1>Turn your documents into<br>searchable, <em>connected</em><br>knowledge.</h1><p class="hero-description">Upload your documents, search across your entire knowledge library,<br class="desktop-break"> ask questions, and get AI-powered answers grounded in the original sources.</p><div class="hero-actions">${cta(config)}<a class="button secondary" href="#how-it-works">See How It Works <span aria-hidden="true">↓</span></a></div><p class="hero-note">Your library. Answers with citations. Evidence within reach.</p>${demo()}<div class="workflow" aria-label="Knowdexia workflow"><span>Documents</span><i>→</i><span>Knowledge library</span><i>→</i><span>Semantic search + AI</span><i>→</i><span>Grounded answers</span><i>→</i><span>Original sources</span></div><p class="caption">Illustrative workflow. Generated AI answers require a configured provider; cited extracts are available without one.</p></section>
<section class="problem section"><div class="container split"><div><div class="eyebrow">LESS SEARCHING. MORE UNDERSTANDING.</div><h2>Your knowledge is scattered<br>across documents.</h2></div><div><p class="lead">The insight is there. Finding it is the hard part.</p><p>It’s buried in PDFs, Word documents, spreadsheets, notes, reports, technical documentation, and research. Keyword search needs the right words. A chat response can leave you wondering where the answer came from.</p><p>Knowdexia brings <strong>semantic retrieval, AI reasoning, and source navigation</strong> into one connected workflow.</p></div></div></section>
<section class="section container" id="how-it-works"><div class="section-heading"><div><div class="eyebrow">FROM FILES TO UNDERSTANDING</div><h2>A clearer path to what you know.</h2></div><p>Four steps. One continuous thread<br>back to the source.</p></div><div class="steps">${steps.map(([t,p],i)=>`<article><span class="step-number">0${i+1}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section>
<section class="section container" id="capabilities"><div class="feature-grid"><div class="feature-copy"><div class="eyebrow">01 / DISCOVER</div><h2>Search by meaning,<br>not just keywords.</h2><p>You shouldn’t need to guess the exact terminology in a document. Find related ideas, even when they’re expressed in different words.</p><p>Knowdexia combines semantic similarity with keyword matching to bring relevant passages into view.</p><a class="text-link" href="/semantic-search">Explore semantic search ${arrow}</a></div><div class="semantic-visual"><div class="tiny">ONE QUESTION</div><div class="meaning-question">“How can we improve visibility<br>in AI recommendations?”</div><div class="connection-line" aria-hidden="true"></div><div class="meaning-core">Meaning connects the dots</div><div class="concepts"><span>LLM visibility</span><span>AI discovery</span><span>Recommendation relevance</span><span>Generative search optimization</span><span>Model citations</span></div><p class="caption">Illustrative related concepts. Results depend on your source material.</p></div></div></section>
<section class="section ask-section"><div class="container feature-grid"><div class="rag-visual"><div class="rag-question">How do these findings fit together?</div><div class="rag-line" aria-hidden="true">↓</div><div class="tiny">SEMANTIC RETRIEVAL</div><div class="document-row"><div><span>PDF</span>Research<br>report</div><div><span>DOCX</span>Product<br>brief</div><div><span>MD</span>Technical<br>notes</div></div><div class="rag-line" aria-hidden="true">↓</div><div class="rag-result"><span aria-hidden="true">✳</span> AI reasoning <span>→</span> Cited answer <b>[1] [2] [3]</b></div><p class="caption">With a configured AI provider</p></div><div class="feature-copy"><div class="eyebrow">02 / UNDERSTAND</div><h2>Ask your entire<br>knowledge library.</h2><p>Some answers don’t live in a single file. Ask across documents and bring the relevant pieces together.</p><p>Knowdexia retrieves source passages, then uses a configured AI provider to construct an answer from that context—with citations you can follow.</p><a class="text-link" href="/multi-document-search">See multi-document knowledge in action ${arrow}</a></div></div></section>
<section class="section container evidence-section"><div class="section-heading"><div><div class="eyebrow">03 / VERIFY</div><h2>Answers you can verify.</h2></div><p>AI answers are more useful when you can<br>see the evidence behind them.</p></div><div class="evidence-grid"><div><div class="evidence-flow">Ask <span>→</span> Answer <span>→</span> <em>Source</em></div><p>Knowdexia doesn’t stop at generating an answer. Citations preserve the connection to the original evidence.</p><p>Go back to the document, inspect the relevant passage, and make your own judgment. Available location details include pages, headings, sheets, and rows, depending on the format.</p><a class="text-link" href="#source-preview">Try the citations in the example above ↑</a></div><blockquote><span class="tiny">THE EVIDENCE STAYS IN VIEW</span><p>“Support claims with <mark>original evidence.</mark> Give readers a direct path from an explanation to its underlying research.”</p><footer><span class="file-type">PDF</span> AI discovery report · Page 8<br><small>Illustrative source passage</small></footer></blockquote></div></section>
<section class="section library-section"><div class="container feature-grid"><div class="feature-copy"><div class="eyebrow">04 / KEEP BUILDING</div><h2>One place for the<br>knowledge that matters.</h2><p>Build a persistent library you can return to. Organize documents into collections, focus your search, and keep adding what’s useful.</p><p class="strong-statement">Don’t just chat with your documents.<br>Build knowledge from them.</p><a class="text-link" href="/ai-knowledge-base">Meet your AI knowledge base ${arrow}</a></div><div class="collection-visual"><div class="collection-title">${mark}<strong>Knowledge library</strong><span>Example collections</span></div>${['AI research','Product documentation','Technical designs','Market research','Reports'].map((s,i)=>`<div class="collection-row"><span class="folder" aria-hidden="true">▱</span><span>${s}</span><span class="collection-format">${['PDF · MD','DOCX · HTML','MD · PDF','XLSX · PDF','CSV · DOCX'][i]}</span></div>`).join('')}<div class="collection-bottom">PDF · DOCX · XLSX · XLS · CSV · Markdown · HTML · TXT</div></div></div></section>
<section class="section container"><div class="section-heading"><div><div class="eyebrow">A MORE CONNECTED APPROACH</div><h2>Beyond finding a file.</h2></div><p>Search, understanding, and evidence.<br>Built to work together.</p></div><div class="table-scroll" role="region" aria-label="Capability comparison" tabindex="0"><table><caption>Typical patterns across approaches; individual tools vary.</caption><thead><tr><th scope="col">Capability</th><th scope="col">Keyword search</th><th scope="col">Generic document chat</th><th scope="col">Knowdexia</th></tr></thead><tbody>${comparisons.map(r=>`<tr>${r.map((v,i)=>i===0?`<th scope="row">${v}</th>`:`<td>${i===3?'<span class="check" aria-hidden="true">✓</span> ':''}${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>
<section class="section container availability"><div><div class="eyebrow">BUILT TODAY. ROOM TO GROW.</div><h2>Know what’s available.</h2><p>The current application is a local document knowledge library.</p></div><div><h3><span class="status-dot"></span> Available now</h3><p>File uploads, persistent collections, semantic + keyword retrieval, multi-document scope, cited extracts, AI-generated answers with a configured provider, and source navigation.</p><h3 class="planned-heading">Coming later · not available today</h3><p>Hosted accounts, shared team workspaces, and external connectors. No release dates are announced.</p></div></section>
<section class="section container explore"><div class="eyebrow">GO DEEPER</div><h2>More ways to work with what you know.</h2><div class="topic-links">${topics.map(t=>`<a href="/${t.slug}">${t.label} ${arrow}</a>`).join('')}</div></section>${closing(config)}`});
}
function closing(config){ return `<section class="closing"><div class="container"><div class="eyebrow">YOUR NEXT ANSWER STARTS WITH WHAT YOU KNOW</div><h2>From a collection of documents<br>to a connected body of knowledge.</h2><p>Search across your knowledge. Ask questions. Get grounded answers.<br>Go directly back to the source.</p>${cta(config)}</div></section>`; }
export function topicPage(config, t){ return layout(config,{path:`/${t.slug}`,title:`${t.label} — Knowdexia`,description:t.description,body:`<article class="article container"><a class="breadcrumb" href="/">Knowdexia /</a><div class="eyebrow">${t.label.toUpperCase()}</div><h1>${t.title}</h1><p class="article-intro">${t.intro}</p><div class="article-body">${t.sections.map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join('')}<aside class="article-note">Searchable knowledge stays useful when you can inspect its sources. <a href="/#source-preview">Explore the interactive citation example.</a></aside></div></article><section class="container related"><h2>Keep exploring</h2><div class="topic-links">${topics.filter(x=>x.slug!==t.slug).slice(0,3).map(x=>`<a href="/${x.slug}">${x.label} ${arrow}</a>`).join('')}</div></section>${closing(config)}`}); }
export function basicPage(config, path, title, description, contents, noindex=false){return layout(config,{path,title:`${title} — Knowdexia`,description,noindex,body:`<article class="article container"><a class="breadcrumb" href="/">Knowdexia /</a><h1>${title}</h1><p class="article-intro">${description}</p><div class="article-body">${contents}</div></article>`});}
export function allPages(config){
return [
 {path:'/',html:home(config)},
 ...topics.map(t=>({path:`/${t.slug}`,html:topicPage(config,t)})),
 {path:'/about',html:basicPage(config,'/about','Documents are the start. Knowledge is the goal.','Knowdexia is a document-centered knowledge platform for people who need to find, connect, and verify information.',`<section><h2>A second brain with sources attached</h2><p>Research, project notes, documentation, and reports become more useful when you can ask questions across them. Knowdexia combines a persistent document library, semantic retrieval, and cited answers in one workflow.</p><p>It is designed for researchers, developers, consultants, analysts, students, and other knowledge workers. The current application runs locally; shared hosted workspaces are not yet available.</p></section><section><h2>Built on document intelligence</h2><p>Knowdexia builds on concepts developed for DocuLocate. DocuLocate focuses on search and navigation within a document. Knowdexia extends that approach to knowledge discovery and AI reasoning across a document library.</p></section><section><h2>Evidence remains part of the answer</h2><p>Source citations help you inspect the supporting material. They are a route to verification, not a guarantee of correctness. Keep the source, context, and your own judgment in the loop.</p></section><p>${cta(config)}</p>`)},
 {path:'/coming-soon',html:basicPage(config,'/coming-soon','Knowdexia is coming soon.','Knowdexia is not open to the public yet. Leave your details and we will tell you when it is ready.',comingSoon(config))},
 ...['privacy','terms'].map(kind=>({path:`/${kind}`,html:legal(config,kind),noindex:!config.legalApproved})),
 {path:'/404',html:basicPage(config,'/404','That page isn’t in the library.','The page may have moved, or the address may be incomplete.',`<p><a class="button primary" href="/">Back to Knowdexia <span aria-hidden="true">→</span></a></p><section><h2>Find your next step</h2><p><a href="/semantic-search">Explore semantic search</a>, learn about <a href="/ai-knowledge-base">AI knowledge bases</a>, or <a href="/coming-soon">get updates on Knowdexia</a>.</p></section>`,true),noindex:true}
];
}
function comingSoon(config){
const form = config.formUrl ? new URL(config.formUrl) : null;
const embeddable = form?.hostname === 'docs.google.com';
if (embeddable) form.searchParams.set('embedded','true');
const signup = !form ? '<p>Sign-up opens soon. Check back shortly.</p>'
  : embeddable ? `<div class="form-card"><iframe src="${escape(form.href)}" title="Knowdexia updates sign-up form" loading="lazy">Loading…</iframe></div><p class="caption">Prefer a separate page? <a href="${escape(config.formUrl)}" target="_blank" rel="noopener">Open the form in a new tab</a>.</p>`
  : `<p><a class="button primary" href="${escape(config.formUrl)}" target="_blank" rel="noopener">Get updates ${arrow}</a></p>`;
return `<section><h2>What’s coming</h2><p>Upload your documents, search them by meaning, ask questions across your library, and follow cited answers back to the original source passages.</p></section><section><h2>Get notified when it’s ready</h2>${signup}${form?'<p class="caption">We will use your details only to tell you about Knowdexia.</p>':''}</section><section><h2>In the meantime</h2><p>Explore <a href="/semantic-search">semantic search</a>, <a href="/ai-knowledge-base">AI knowledge bases</a>, or <a href="/#source-preview">try the interactive example</a> on the home page.</p></section>`;
}
function legal(config,kind){const privacy=kind==='privacy';return basicPage(config,`/${kind}`,privacy?'Privacy':'Terms',config.legalApproved?(privacy?'Privacy information for Knowdexia.':'Terms for using Knowdexia.'):(privacy?'Draft privacy notice for review — data handling for the marketing website and separate application.':'Draft terms for review — responsible use, service availability, and items to finalize before launch.'),privacy?`<aside class="article-note"><strong>Before public launch:</strong> the operator must provide its legal identity, contact details, hosting and logging practices, retention periods, and applicable rights process. This draft does not establish those facts.</aside><section><h2>This marketing website</h2><p>This implementation includes no analytics scripts, advertising pixels, contact forms, authentication, or application document uploads. Hosting infrastructure may process requests and logs; the operator must describe those practices in the final policy.</p></section><section><h2>The separate application</h2><p>The inspected local Knowdexia application persists documents and indexes on the computer running it. When an external AI provider is configured, questions and selected source passages can be sent to that provider. The operator must disclose the actual deployment configuration and provider policies before offering a hosted service.</p></section><section><h2>Questions and data requests</h2><p>An operator contact and any applicable request procedures must be added before this policy is finalized.</p></section>`:`<aside class="article-note"><strong>Before public launch:</strong> replace this draft with terms approved for the operator, deployment, and intended jurisdictions. Legal identity, contact details, and effective date remain to be supplied.</aside><section><h2>Website and application</h2><p>This website describes Knowdexia. The application is a separate project, and its availability depends on the deployment provided by its operator. No pricing, subscription, or hosted service commitment is established by this draft.</p></section><section><h2>Responsible use</h2><p>Only upload material you are authorized to use. Review source passages before relying on generated answers; AI output and document extraction may be incomplete or incorrect.</p></section><section><h2>Items to finalize</h2><p>The operator must establish the applicable service terms, content rights, acceptable use rules, liability provisions, termination process, and governing law before public launch.</p></section>`,!config.legalApproved);}
